---
# not really a "horizon service" but horizon is the outlier
#- name: restart horizon services
#  service: name=apache2 state=restarted

#- name: restart apache
#  service: name=apache2 state=restarted

- name: compress horizon assets
  command: tools/with_venv.sh ./manage.py compress
  args:
    chdir: /opt/stack/horizon/
  become: true
  become_user: www-data
