---
- name: restart ironic services
  service: name={{ item }} state=restarted
  when: restart|default(True)
  with_items:
    - ironic-api
    - ironic-conductor

- name: restart tftpd
  service: name=tftpd-hpa state=restarted
