---
- name: refresh cert auths
  command: update-ca-certificates
  when: ursula_os == 'ubuntu'

- name: restart logstash-forwarder
  service: name=logstash-forwarder state=restarted

- name: stop logstash-forwarder
  service: name=logstash-forwarder state=stopped

- name: start logstash-forwarder
  service: name=logstash-forwarder state=started

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart filebeat
  service: name=filebeat state=restarted
  failed_when: false

