---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: ceilometer
    logdata: "{{ ceilometer.logs }}"
  - role: openstack-source
    project_name: ceilometer
    project_rev: "{{ ceilometer.rev | default(openstack_rev) }}"
    alternatives: "{{ ceilometer.alternatives }}"
    python_dependencies: "{{ ceilometer.source.python_dependencies }}"
    constrain: "{{ ceilometer.constrain }}"
    upper_constraints: "{{ ceilometer.upper_constraints | default(openstack_constraints) }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: ceilometer
    alternatives: "{{ ceilometer.alternatives }}"
    when: openstack_install_method == 'package'
  - role: openstack-distro
    project_name: ceilometer
    project_packages: "{{ ceilometer.distro.controller.project_packages }}"
    upper_constraints: "{{ ceilometer.upper_constraints |default(openstack_constraints) }}"
    constrain: "{{ ceilometer.constrain }}"
    when:
      - openstack_install_method == 'distro'
      - inventory_hostname in groups['controller']
  - role: openstack-distro
    project_name: ceilometer
    project_packages: "{{ ceilometer.distro.compute.project_packages }}"
    upper_constraints: "{{ ceilometer.upper_constraints |default(openstack_constraints) }}"
    constrain: "{{ ceilometer.constrain }}"
    when:
      - openstack_install_method == 'distro'
      - inventory_hostname in groups['compute']
