---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: openstack-source
    project_name: cinder
    project_rev: "{{ cinder.rev |default(openstack_rev) }}"
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    system_dependencies: "{{ cinder.source.system_dependencies }}"
    python_dependencies: "{{ cinder.source.python_dependencies }}"
    constrain: "{{ cinder.constrain }}"
    upper_constraints: "{{ cinder.upper_constraints |default(openstack_constraints) }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: cinder
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    when: openstack_install_method == 'package'
  - role: ceph-defaults
    when: ceph.enabled
  - role: openstack-distro
    project_name: cinder
    project_packages: "{{ cinder.distro.project_packages }}"
    upper_constraints: "{{ cinder.upper_constraints |default(openstack_constraints) }}"
    constrain: "{{ cinder.constrain }}"
    rootwrap: True
    when: openstack_install_method == 'distro'
