---
dependencies:
  - role: openstack-meta
  - role: endpoints
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.cloud_archive.repo }} {{ ansible_distribution_release }}-updates/mitaka main'
        key_package: ubuntu-cloud-keyring
    when: os == 'ubuntu'
  - role: sensu-check
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: nova
    logdata: "{{ nova.logs }}"
  - role: openstack-source
    project_name: nova
    project_rev: "{{ nova.source.rev }}"
    rootwrap: True
    alternatives: "{{ nova.alternatives }}"
    system_dependencies: "{{ nova.source.system_dependencies }}"
    python_dependencies: "{{ nova.source.python_dependencies }}"
    constrain: "{{ nova.source.constrain }}"
    upper_constraints: "{{ nova.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: nova
    rootwrap: True
    alternatives: "{{ nova.alternatives }}"
    when: openstack_install_method == 'package'
  - role: openstack-distro
    project_name: nova
    osp_packages:
      - 'openstack-nova-compute'
    rootwrap: True
    when:
      - openstack_install_method == 'distro'
      - inventory_hostname in groups['compute']
  - role: openstack-distro
    project_name: nova
    osp_packages:
      - 'openstack-nova-api'
      - 'openstack-nova-cells'
      - 'openstack-nova-conductor'
      - 'openstack-nova-console'
      - 'openstack-nova-scheduler'
      - 'openstack-nova-novncproxy'
      - 'openstack-nova-placement-api'
    rootwrap: True
    when:
      - openstack_install_method == 'distro'
      - inventory_hostname in groups['controller']