---
dependencies:
  - role: endpoints
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: horizon
    logdata: "{{ horizon.logs }}"
  - role: openstack-source
    project_name: horizon
    project_rev: "{{ horizon.rev |default(openstack_rev) }}"
    system_dependencies: "{{ horizon.source.system_dependencies }}"
    python_dependencies: "{{ horizon.source.python_dependencies }}"
    constrain: "{{ horizon.constrain }}"
    upper_constraints: "{{ horizon.upper_constraints |default(openstack_constraints) }}"
    additional_handlers: [ "compress horizon assets" ]
    python_post_dependencies: "{{ horizon.source.python_post_dependencies }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: horizon
    when: openstack_install_method == 'package'
  - role: openstack-distro
    project_name: horizon
    project_packages: "{{ horizon.distro.project_packages }}"
    python_post_dependencies: "{{ horizon.distro.python_post_dependencies }}"
    upper_constraints: "{{ horizon.upper_constraints |default(openstack_constraints) }}"
    constrain: "{{ horizon.constrain }}"
    when: openstack_install_method == 'distro'
  - role: apache
  - role: keystone-defaults
  - role: openstack-firewall
    rule_name: horizon
    rules_type_input:
      - { protocol: tcp, port: 80 }
      - { protocol: tcp, port: 443 }
